server {
  listen @@GATEWAY_PORT@@;
  server_name _;

  location = /healthz {
    access_log off;
    default_type application/json;
    return 200 '{"ok":true,"service":"gateway"}';
  }

  location /api/ {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://@@CONDUCTOR_API@@/api/;
  }

  location /swagger-ui/ {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://@@CONDUCTOR_API@@/swagger-ui/;
  }

  location /actuator/ {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://@@CONDUCTOR_API@@/actuator/;
  }

  location /review/ {
    rewrite ^/review/(.*)$ /$1 break;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://@@REVIEW_SERVICE@@;
  }

  location / {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://@@CONDUCTOR_UI@@/;
  }
}
