conductor.db.type=postgres
spring.datasource.url=jdbc:postgresql://conductor-postgres:5432/${POSTGRES_DB:conductor}
spring.datasource.username=${POSTGRES_USER:conductor}
spring.datasource.password=${POSTGRES_PASSWORD:conductor}
conductor.postgres.schema=public

conductor.queue.type=postgres
conductor.indexing.enabled=true
conductor.indexing.type=opensearch2
conductor.opensearch.version=2
conductor.opensearch.url=http://opensearch:9200
conductor.opensearch.indexPrefix=conductor
conductor.opensearch.indexShardCount=1
conductor.opensearch.indexReplicasCount=0
conductor.opensearch.clusterHealthColor=yellow
conductor.opensearch.autoIndexManagementEnabled=true

conductor.app.workflowExecutionLockEnabled=true
conductor.workflow-execution-lock.type=postgres

conductor.postgres.pollDataFlushInterval=5000
conductor.postgres.pollDataCacheValidityPeriod=5000
conductor.postgres.onlyIndexOnStatusChange=true
conductor.postgres.experimentalQueueNotify=true
conductor.postgres.experimentalQueueNotifyStalePeriod=5000

conductor.app.taskIndexingEnabled=true
conductor.app.activeWorkerLastPollTimeout=10000

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.health.elasticsearch.enabled=false
management.prometheus.metrics.export.enabled=true
