apiVersion: 1

datasources:
  - name: VictoriaMetrics
    uid: victoria-metrics
    type: prometheus
    access: proxy
    url: http://victoria-metrics:8428
    isDefault: true
    editable: true

  - name: VictoriaLogs
    uid: victoria-logs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://victoria-logs:9428
    editable: true
